unlaunch theme: loveless
DS-Homebrew/twlmenu-extras pull request #227
Opened 2024-12-14 16:44 UTC by boyloftus

my bloody valentine's 1991 record, "loveless".
![loveless](https://github.com/user-attachments/assets/24868d8a-2576-45b9-bdda-2bda4b7eab36)

2024-12-14 18:43 UTC, boyloftus commented
I've added more themes to this pull for a total of 4 themes :)

> loveless.gif
title: mbv - loveless
desc: my bloody valentine's 1991 record, "loveless".
author: boyloftus

>aphex.gif
title: Selected Unlaunch Works 17-25
desc: Parody of "Selected Ambient Works 85-92"
author: boyloftus

>ggxrd.gif
title: Guity Gear XRD
desc: Sol Badguy art from the games banner
author: boyloftus

>draingg.gif
title: DRAINGG
desc: GTBSG
author: boyloftus

2025-08-05 04:27 UTC, Ozdotdotdot commented
These themes are great! What did you use to make them? The Sol Badguy one especially. Simplicity of the black one is nice too

2025-08-10 15:59 UTC, radicalhiway commented
> These themes are great! What did you use to make them? The Sol Badguy one especially. Simplicity of the black one is nice too

I made the first one (my bloody valentine theme) with photoshop, but found out the DSi hacking dicsord has a bot that auto formats images to work with unlaunch so I did the rest with that :) thank you for the kind words about my themes! <3

2026-01-17 20:32 UTC, Epicpkmn11 requested changes
Please add the metadata too [_meta.json](https://github.com/radicalhiway/boyloftus-unlaunch-themes/blob/master/_nds/TWiLightMenu/unlaunch/backgrounds/_meta.json)

2026-07-04 20:40 UTC, Epicpkmn11 commented
Added in 13c8792c79fa64e65acd70283c811f0f0e0f8225

2026-07-04 20:40 UTC, closed without merging